# https://taskfile.dev

version: '3'

tasks:
  install_linux:
    cmds:
      - cat apps/linux/test_env.nix | xargs -I {} nix profile install --impure {}

  install_mac_os:
    cmds:
      - brew bundle -f apps/mac_os/Brewfile

  install_windows:
    cmds:
      - choco install apps/windows/packages.config -y