# https://taskfile.dev

version: '3'

tasks:
  install_linux:
    cmds:
     - cat apps/linux/flatpak.txt | xargs -I {} flatpak install -y --noninteractive {}
      - cat apps/linux/env.nix | xargs -I {} nix profile install --impure {}

  install_mac_os:
    cmds:
      - brew bundle -f apps/mac_os/Brewfile

  install_windows:
    cmds:
      - choco install apps/windows/packages.config -y

    nixos_remove_old:
      cmds:
        - sudo nix-collect-garbage --delete-old

    list_nix_channels:
      cmds:
        - nix-channel --list

    update_nix_channels:
      cmds:
        - nix-channel --update

    